#!/bin/bash
# DCRAB SOFTWARE
# Version: 2.0
# Autor: CC-staff
# Donostia International Physics Center
#
# ===============================================================================================================
#
# DCRAB main script 
#
# ===============================================================================================================


# Check if binary path is defined
if [ -z "$DCRAB_BIN" ]; then
    echo "ERROR: DCRAB_BIN undefined"
    exit 
fi

# Check arguments
case "$1" in
	start)
		echo "--- Start DCRAB output (start fase) ---"

		# Load necessary functions
		source $DCRAB_BIN/scripts/dcrab_config.sh
		source $DCRAB_BIN/scripts/dcrab_report_functions.sh

		# Check which scheduler use the system
		dcrab_check_scheduler

		# Initialize environment
		dcrab_init_variables 0

 		# Move to working directory
		cd $DCRAB_WORKDIR
		mkdir -p $DCRAB_REPORT_DIR/log

		# Initialize log report of the main node
		echo "--- DCRAB main-node: `hostname` log ---" >> $DCRAB_LOG_DIR/dcrab.log

		# Create report files
		dcrab_create_report_files >> $DCRAB_LOG_DIR/dcrab.log 2>&1 

		# Launch processes in each node to collect data
		dcrab_start_data_collection  >> $DCRAB_LOG_DIR/dcrab.log 2>&1
	
		echo "--- End DCRAB output (start fase)---"
   	;;
	finish)
		echo "--- Start DCRAB output (finish fase) ---"
		
		# Load necessary functions
		source $DCRAB_BIN/scripts/dcrab_finalize.sh
		source $DCRAB_BIN/scripts/dcrab_config.sh

		# Check which scheduler use the system
		dcrab_check_scheduler

		# Initialize some necessary variables
                dcrab_init_variables 0

   		# Move to working directory
		cd $DCRAB_WORKDIR

		# Finalize DCRAB
		dcrab_finalize >> $DCRAB_LOG_DIR/dcrab.log 2>&1

		echo "--- End DCRAB output (finish fase) ---"
   	;;
	istart)
		# Load necessary functions
                source $DCRAB_BIN/scripts/dcrab_config.sh
                source $DCRAB_BIN/scripts/dcrab_report_functions.sh

                # Check which scheduler use the system
                dcrab_check_scheduler

                # Initialize some necessary (only internal mode enabled)
                dcrab_init_variables 1 
		
		mkdir -p $DCRAB_REPORT_DIR/log

		# Create report files
                dcrab_create_report_files >> $DCRAB_LOG_DIR/dcrab.log 2>&1

                # Launch processes in each node to collect data
                dcrab_start_data_collection  >> $DCRAB_LOG_DIR/dcrab.log 2>&1
	;;
	ifinish)
		# Load necessary functions
                source $DCRAB_BIN/scripts/dcrab_finalize.sh
                source $DCRAB_BIN/scripts/dcrab_config.sh

                # Check which scheduler use the system
                dcrab_check_scheduler

		# Initialize some necessary variables (only internal mode enabled)
                dcrab_init_variables 1

                # Finalize DCRAB
                dcrab_finalize >> $DCRAB_LOG_DIR/dcrab.log 2>&1

	;;
	version)
		cat $DCRAB_BIN/../config/version
	;;
	*)
		echo "DCRAB report help"
		echo "Developed by DIPC Fundation, CC-staff"
		echo ""
		echo $"Usage: $0 {start|finish|version}"
		echo ""
		echo "Summary:"
		echo "    * start    | starts DCRAB report"
		echo "    * finish   | finalize data collection and DCRAB processes"
		echo "    * version  | displays DCRAB version"
		echo " "
		echo "For sysadmins: "
		echo "    * istart   | starts DCRAB only for internal report"
		echo "    * ifinish  | finalize internal data collection and DCRAB processes"
		echo ""
    	exit 1
esac

