#!/bin/bash
# DCRAB SOFTWARE
# Version: 2.0
# Author: CC-staff
# Donostia International Physics Center
#
# ===============================================================================================================
#
# DCRAB main script 
#
# ===============================================================================================================

if [ -z "$DCRAB_PATH" ]; then
    echo "ERROR: DCRAB_PATH undefined"
    exit 1
fi

case "$1" in
    start)
        source $DCRAB_PATH/src/scripts/dcrab_config.sh
        source $DCRAB_PATH/src/scripts/dcrab_report_functions.sh

        dcrab_check_scheduler
        dcrab_init_variables 0

        cd $DCRAB_WORKDIR
        mkdir -p $DCRAB_REPORT_DIR/log

        # Initialize log report of the main node
        echo "--- DCRAB main-node: `hostname` log ---" >> $DCRAB_LOG_DIR/dcrab.log

        dcrab_create_report_files >> $DCRAB_LOG_DIR/dcrab.log 2>&1 
        dcrab_start_data_collection  >> $DCRAB_LOG_DIR/dcrab.log 2>&1
        ;;
    finish)
        source $DCRAB_PATH/src/scripts/dcrab_finalize.sh
        source $DCRAB_PATH/src/scripts/dcrab_config.sh

        dcrab_check_scheduler
        dcrab_init_variables 0

        cd $DCRAB_WORKDIR

        dcrab_finalize >> $DCRAB_LOG_DIR/dcrab.log 2>&1
        ;;
    istart)
        source $DCRAB_PATH/src/scripts/dcrab_config.sh
        source $DCRAB_PATH/src/scripts/dcrab_report_functions.sh

        dcrab_check_scheduler
        dcrab_init_variables 1 
      
        mkdir -p $DCRAB_REPORT_DIR/log

        dcrab_create_report_files >> $DCRAB_LOG_DIR/dcrab.log 2>&1
        dcrab_start_data_collection  >> $DCRAB_LOG_DIR/dcrab.log 2>&1
        ;;
    ifinish)
        source $DCRAB_PATH/src/scripts/dcrab_finalize.sh
        source $DCRAB_PATH/src/scripts/dcrab_config.sh

        dcrab_check_scheduler
        dcrab_init_variables 1
        dcrab_finalize >> $DCRAB_LOG_DIR/dcrab.log 2>&1
        ;;
    version)
        cat $DCRAB_PATH/config/version
        ;;
    *)
        echo "DCRAB reporting tool help"
        echo "Developed by DIPC Foundation, CC-staff"
        echo ""
        echo $"Usage: $0 {start|finish|version}"
        echo ""
        echo "Summary:"
        echo "    * start    | starts DCRAB report"
        echo "    * finish   | finalize data collection and DCRAB processes"
        echo "    * version  | displays DCRAB version"
        echo " "
        echo "For sysadmins: "
        echo "    * istart   | starts DCRAB only for internal report"
        echo "    * ifinish  | finalize internal data collection and DCRAB processes"
        echo ""
        exit 1
esac

exit 0
