#!/bin/bash


# Check if binary path is defined
if [ -z "$DCRAB_BIN" ]; then
    echo "ERROR: DCRAB_BIN undefined"
    exit
fi

# Configuration functions
source $DCRAB_BIN/scripts/dcrab_config.sh 

# Check arguments
case "$1" in
	start)
        	# Initialize dcrab report
		dcrab_start_report

		# Launch processes in each node to collect data
		dcrab_start_data_collection

		# Save environment
		dcrab_save_environment "DCRAB_"
            	;;
	finish)
		# Finalize DCRAB
		dcrab_finalize
            	;;
        *)
		echo "DCRAB report help"
		echo "Developed by DIPC Fundation, CC-staff"
		echo ""
                echo $"Usage: $0 {start|finish}"
		echo ""
		echo "Summary:"
		echo "    * start 		| starts dcrap report"
		echo "    * finish 		| finalize data collection and dcrap processes"
		echo ""
            	exit 1
esac

